/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.LoginController.login;
import java.sql.Connection;
import static java.sql.DriverManager.getConnection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DBConnection;
import static model.DBConnection.getConnection;


/**
 *
 * @author user
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        
         this.setUndecorated(true);
        initComponents();
        name.setBackground(new java.awt.Color(0,0,0,1));
        MiddleName.setBackground(new java.awt.Color(0,0,0,1));
        LastName.setBackground(new java.awt.Color(0,0,0,1));
        StudentId.setBackground(new java.awt.Color(0,0,0,1));
        StudentAddress.setBackground(new java.awt.Color(0,0,0,1));
        StudentEmail.setBackground(new java.awt.Color(0,0,0,1));
        userName.setBackground(new java.awt.Color(0,0,0,1));
        Password.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newJPanel1 = new com.NewJPanel();
        tittle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MiddleName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        StudentId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        StudentEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        StudentAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        ClearButton3 = new javax.swing.JButton();
        SubmitButton1 = new javax.swing.JButton();
        Backtologinbutton = new javax.swing.JButton();
        Cancelwindow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("WELCOME  TO THE EDUVERSE");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SCHOOL MANAGMENT SYSTEM ");
        jLabel1.setAutoscrolls(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cherry-sushi-lunch-at-work.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 800));

        newJPanel1.setBackground(new java.awt.Color(0, 102, 255));
        newJPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("Create Account");
        tittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        newJPanel1.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 500, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Let's get started on this exciting journey together!");
        newJPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 39, 568, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name :");
        newJPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 105, 116, 47));

        name.setFont(name.getFont().deriveFont(name.getFont().getSize()+2f));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newJPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 118, 399, 25));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("________________________________________________________");
        newJPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 137, 449, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Middle Name:");
        newJPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 173, 132, 47));

        MiddleName.setFont(MiddleName.getFont().deriveFont(MiddleName.getFont().getSize()+2f));
        MiddleName.setForeground(new java.awt.Color(255, 255, 255));
        MiddleName.setBorder(null);
        newJPanel1.add(MiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 186, 399, 25));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("________________________________________________________");
        newJPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 205, 449, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("________________________________________________________");
        newJPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 273, 449, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Last Name:");
        newJPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 241, 116, 47));

        LastName.setFont(LastName.getFont().deriveFont(LastName.getFont().getSize()+2f));
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setBorder(null);
        newJPanel1.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 254, 399, 25));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("________________________________________________________");
        newJPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 341, 449, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Student ID:");
        newJPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 116, 47));

        StudentId.setFont(StudentId.getFont().deriveFont(StudentId.getFont().getSize()+2f));
        StudentId.setForeground(new java.awt.Color(255, 255, 255));
        StudentId.setBorder(null);
        newJPanel1.add(StudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 322, 399, 25));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("________________________________________________________");
        newJPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 409, 449, -1));

        StudentEmail.setFont(StudentEmail.getFont().deriveFont(StudentEmail.getFont().getSize()+2f));
        StudentEmail.setForeground(new java.awt.Color(255, 255, 255));
        StudentEmail.setBorder(null);
        newJPanel1.add(StudentEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 390, 399, 25));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Student E-mail:");
        newJPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 377, 142, 47));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("________________________________________________________");
        newJPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 477, 449, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Student Address:");
        newJPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 445, -1, 47));

        StudentAddress.setFont(StudentAddress.getFont().deriveFont(StudentAddress.getFont().getSize()+2f));
        StudentAddress.setForeground(new java.awt.Color(255, 255, 255));
        StudentAddress.setBorder(null);
        newJPanel1.add(StudentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 458, 399, 25));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("________________________________________________________");
        newJPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 545, 449, -1));

        userName.setFont(userName.getFont().deriveFont(userName.getFont().getSize()+2f));
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setBorder(null);
        newJPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 526, 399, 25));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("User Name:");
        newJPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 513, 116, 47));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("________________________________________________________");
        newJPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 613, 449, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Password:");
        newJPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 581, 116, 47));

        Password.setFont(Password.getFont().deriveFont(Password.getFont().getSize()+2f));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        newJPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 594, 399, 25));

        ExitButton.setBackground(new java.awt.Color(71, 59, 220));
        ExitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        newJPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 690, 100, 40));

        ClearButton3.setBackground(new java.awt.Color(71, 59, 220));
        ClearButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ClearButton3.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton3.setText("Clear");
        ClearButton3.setBorder(null);
        ClearButton3.setBorderPainted(false);
        ClearButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButton3ActionPerformed(evt);
            }
        });
        newJPanel1.add(ClearButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 90, 40));

        SubmitButton1.setBackground(new java.awt.Color(71, 59, 220));
        SubmitButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SubmitButton1.setForeground(new java.awt.Color(255, 255, 255));
        SubmitButton1.setText("Submit");
        SubmitButton1.setBorder(null);
        SubmitButton1.setBorderPainted(false);
        SubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButton1ActionPerformed(evt);
            }
        });
        newJPanel1.add(SubmitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 130, 40));

        Backtologinbutton.setBackground(new java.awt.Color(71, 59, 220));
        Backtologinbutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Backtologinbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backtologinbutton.setText("Back to login");
        Backtologinbutton.setBorder(null);
        Backtologinbutton.setBorderPainted(false);
        Backtologinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktologinbuttonActionPerformed(evt);
            }
        });
        newJPanel1.add(Backtologinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, 140, 40));

        Cancelwindow.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Cancelwindow.setForeground(new java.awt.Color(255, 255, 255));
        Cancelwindow.setText("   X");
        Cancelwindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelwindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelwindowMouseClicked(evt);
            }
        });
        newJPanel1.add(Cancelwindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 30));

        getContentPane().add(newJPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 0, 641, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ClearButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButton3ActionPerformed
    clearFields();
    }//GEN-LAST:event_ClearButton3ActionPerformed

    private void SubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButton1ActionPerformed
      String FIRSTNAME = name.getText();
      String MIDDLENAME = MiddleName.getText();
      String LASTENAME = LastName.getText();
      String STUDENTID = StudentId.getText(); 
      String STUDENTEMAIL =  StudentEmail.getText();
      String STUDENTADDRESS =  StudentAddress.getText();
      String USERNAME =  userName.getText();
      String PASSWORD =  Password.getText();
      
     if (FIRSTNAME.isEmpty() ||MIDDLENAME.isEmpty()||LASTENAME.isEmpty()|| STUDENTID.isEmpty()||STUDENTEMAIL.isEmpty()|| STUDENTADDRESS.isEmpty()||USERNAME.isEmpty()|| PASSWORD.isEmpty()) {
        // Show an error message for empty fields
        JOptionPane.showMessageDialog(this, "Fill up the form properly", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!isPasswordStrong(PASSWORD)) {
        // Show an error message for weak password
        JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long and contain at least one number, one uppercase letter, one lowercase letter, and one special character", "Error", JOptionPane.ERROR_MESSAGE);
    } else{
         //start the regiter process
         userregister(FIRSTNAME,MIDDLENAME,LASTENAME,STUDENTID,STUDENTEMAIL,STUDENTADDRESS, USERNAME,PASSWORD);
         clearFields();
         
     }  

    }//GEN-LAST:event_SubmitButton1ActionPerformed

    private void BacktologinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktologinbuttonActionPerformed
 new view.userlogin().setVisible(true);
        dispose();    
    }//GEN-LAST:event_BacktologinbuttonActionPerformed

    private void CancelwindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelwindowMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CancelwindowMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 for (double i = 0.0; i <=1.0; i = i+0.1){
        String val = i+"";
        float f = Float.valueOf(val);
        this.setOpacity(f); 
        try{
            Thread.sleep(50);
        } catch(Exception e) {
         
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    
    private void clearFields() {
    name.setText("");
    MiddleName.setText("");
    LastName.setText("");
    StudentId.setText("");
    StudentEmail.setText("");
    StudentAddress.setText("");
   userName.setText("");
   Password.setText("");
    
}  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backtologinbutton;
    private javax.swing.JLabel Cancelwindow;
    private javax.swing.JButton ClearButton3;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField StudentAddress;
    private javax.swing.JTextField StudentEmail;
    private javax.swing.JTextField StudentId;
    private javax.swing.JButton SubmitButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private com.NewJPanel newJPanel1;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    private void userregister(String FIRSTNAME, String MIDDLENAME, String LASTENAME, String STUDENTID, String STUDENTEMAIL, String STUDENTADDRESS, String USERNAME, String PASSWORD) {
       Connection dbconn = DBConnection.getConnection();
    if(dbconn != null){
        try {
            PreparedStatement st = (PreparedStatement)
                    dbconn.prepareStatement("INSERT INTO users (Student_FirstName,Student_MiddleName,Student_LastName,Student_Id ,Student_Email,Student_Address,Student_UserName,Student_PassWord) VALUES(?,?,?,?,?,?,?,?)");
            
            st.setString(1, FIRSTNAME);
            st.setString(2,  MIDDLENAME);
            st.setString(3, LASTENAME);
            st.setString(4,  STUDENTID);  
            st.setString(5, STUDENTEMAIL);
            st.setString(6,  STUDENTADDRESS);
            st.setString(7,  USERNAME);
            st.setString(8, PASSWORD);
            
            int res = st.executeUpdate();
            JOptionPane.showMessageDialog(this, "user data inserted.", "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
        System.out.println("The connection not available");
    }

    }
    
    private boolean isPasswordStrong(String password) {
    int passwordLength = password.length();
    boolean hasNumber = false;
    boolean hasUppercase = false;
    boolean hasLowercase = false;
    boolean hasSpecialChar = false;

    if (passwordLength < 8) {
        return false;
    }

    for (char c : password.toCharArray()) {
        if (Character.isDigit(c)) {
            hasNumber = true;
        } else if (Character.isUpperCase(c)) {
            hasUppercase = true;
        } else if (Character.isLowerCase(c)) {
            hasLowercase = true;
        } else if (!Character.isLetterOrDigit(c)) {
            hasSpecialChar = true;
        }
    }

    return hasNumber && hasUppercase && hasLowercase && hasSpecialChar;
}

    }
